# This is example of docker-compose file
# which can be used to run NexentaFusion ecosystem.
#
# Usage:
#   docker-compose up

version: '3.5'

# Database shared environment for all cluster nodes
x-opensearch-env: &opensearch-env
  # Heap size
  OPENSEARCH_JAVA_OPTS: "-Xms1g -Xmx1g"

  # Cluster name
  cluster.name: "opensearch-docker-cluster"

  bootstrap.memory_lock: "true" # along with the memlock settings, disables swapping
  discovery.seed_hosts: "opensearch-node1,opensearch-node2,opensearch-node3"
  cluster.initial_master_nodes: "opensearch-node1,opensearch-node2,opensearch-node3"

services:
  fusion:
    image: nexenta/fusion:${VERSION:-2.0.3}
    container_name: fusion
    restart: always
    environment:
    # If you want NexentaFusion to listen on other port than 8457
    # change environment variable below and do a change in the ports section
    # or just use PORT environment variable to specify port.
    # Example: PORT=443 docker-compose up -d
      PORT: ${PORT:-8457}
    #
    # If you want to specify management address and Elasticsearch info,
    # then uncomment following lines.
    # Note: If settings are defined as environmental variables, then
    # they would be displayed as read-only in UI configuration screens.
    #   MANAGEMENT_ADDRESS: "192.168.10.62"
    #   ELASTICSEARCH_SERVERS: 'https://admin:admin@192.168.10.62:9200'
    #
    # Proxy server address
    #   WEB_PROXY: "http://192.168.10.250:8080"
    volumes:
      - fusdata:/var/lib/nef
    ports:
      - ${PORT:-8457}:8457

  opensearch-node1:
    image: nexenta/fusion-opensearch:1.3.5
    container_name: opensearch-node1
    restart: always
    environment:
      << : *opensearch-env
      node.name: "opensearch-node1"
      plugins.security.ssl.transport.enabled_protocols: "TLSv1.3"
      plugins.security.ssl.http.enabled_protocols: "TLSv1.2, TLSv1.3"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - esdata1:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - esnet

  opensearch-node2:
    image: nexenta/fusion-opensearch:1.3.5
    container_name: opensearch-node2
    restart: always
    environment:
      << : *opensearch-env
      node.name: "opensearch-node2"
      plugins.security.ssl.transport.enabled_protocols: "TLSv1.3"
      plugins.security.ssl.http.enabled_protocols: "TLSv1.2, TLSv1.3"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - esdata2:/usr/share/opensearch/data
    networks:
      - esnet

  opensearch-node3:
    image: nexenta/fusion-opensearch:1.3.5
    container_name: opensearch-node3
    restart: always
    environment:
      << : *opensearch-env
      node.name: "opensearch-node3"
      plugins.security.ssl.transport.enabled_protocols: "TLSv1.3"
      plugins.security.ssl.http.enabled_protocols: "TLSv1.2, TLSv1.3"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - esdata3:/usr/share/opensearch/data
    networks:
      - esnet

volumes:
  fusdata:
    driver: local
  esdata1:
    driver: local
  esdata2:
    driver: local
  esdata3:
    driver: local

networks:
  esnet:
    driver: bridge